### ISSUE TITLE
Adjust page size with aspect_ratio or width and height

### ISSUE THREAD

**Issue by sam7567** [lovelylain/ha-addon-iframe-card#1]
Hello,

Is there anyway to adjust page size with `aspect_ratio` or `width` and `height`. I have been trying this card for Music Assistant as it supports ingress. But unable to customize the width / height.

Similar to :

```
type: iframe
url: /api/hassio_ingress/xxxxx
aspect_ratio: 100%
```

**Comment by lovelylain** [comment]
This card has the same configuration options as the [webpage card](https://www.home-assistant.io/dashboards/iframe/#yaml-configuration), so you can adjust page size with aspect_ratio.

**Comment by sam7567** [comment]
I tried first. Not working. This works only if I add grid from Native HA

```
type: custom:addon-iframe-card
url: XXXXX_music_assistant
aspect_ratio: 100%
grid_options:
  columns: full
  rows: 8
```
