### ISSUE TITLE
iFrame for Music Assistant showing blank card on Tablet / Phone apps but not desktop web browser

### ISSUE THREAD

**Issue by eTron** [lovelylain/ha-addon-iframe-card#4]
Feedback suggests adding    name="ha-main-window"    to the iFrame tag to see if it works.

**Comment by lovelylain** [comment]
show me your configuration yaml.

**Comment by eTron** [comment]
Here is my yaml config. Doesn’t have much.


# Loads default set of integrations. Do not remove.
default_config:

frontend:
 themes: !include_dir_merge_named themes

# Text to speech
tts:
 - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


Jesse

**Comment by lovelylain** [comment]
@eTron I mean, ingress webpage card ui configuration in yaml mode. for example
```yaml
type: custom:addon-iframe-card
url: a0d7b954_nodered/ui/
```

**Comment by zecoj** [comment]
I'm facing the same problem so I'll chime in. My hass_ingress works perfectly from the sidebar or direct url https://some.domain/xxyyzz/

This is my config:

addon-iframe-card
 ```yaml
type: custom:addon-iframe-card
url: /xxyyzz/
```

hass_ingress
```yaml
ingress:
  xxyyzz: 
    ui_mode: normal 
    title: XXYYZZ 
    icon: mdi:monitor-eye 
    url: https://some.domain/ 
    index: somerandomstring1/vnc.html?view_only=true&autoconnect=true&resize=scale&shared=true&path=somerandomstring2/websockify
    headers: 
      Authorization: Basic somerandomstring3
````

**Comment by lovelylain** [comment]
@zecoj https://github.com/lovelylain/hass_ingress?tab=readme-ov-file#features
- Embed in other pages. (url: /api/ingress/{name}/)

use  `/api/ingress/xxyyzz/` instead of `/xxyyzz/`

**Comment by zecoj** [comment]
Yep I already tried that.

With "/api/ingress/xxyyzz/" the iframe redirects to HA's main dashboard. If I use full URL https://some.domain/api/ingress/xxyyzz/ on a new tab, it will also redirect to HA's main dashboard.

With "/api/ingress/musicassistant/" or "/api/ingress/zigbee2mqtt/" it works fine. I'm wondering if it's due to the headers & index combination for xxyyzz?

**Comment by lovelylain** [comment]
```
    url: https://some.domain/ 
    index: somerandomstring1/vnc.html?view_only=true&autoconnect=true&resize=scale&shared=true&path=somerandomstring2/websockify
    headers:
      Host: some.domain # add the Host header
      Authorization: 
```
